model:
  base_params:
    model_name: "together_ai/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
    base_url: "https://api.together.xyz/v1"
    api_key: $TOGETHER_API_KEY # Replace with your actual API key
  generation:
    temperature: 0

# To run:
# python -m lighteval endpoint litellm \
# "endpoint_litellm.yaml" \
# "filbench|global_mmlu_all_tgl_mcf:anatomy|0|0" \
# --custom-tasks community_tasks/filbench_evals.py
