model:
  model_name: "mistralai/Mixtral-8x7B-Instruct-v0.1"
  generation:
    temperature: 0

api:
  base_url: "https://api.together.xyz/v1"
  api_key: $TOGETHER_API_KEY # Replace with your actual API key

# To run:
# python -m lighteval endpoint openai \
# "endpoint_openai.yaml" \
# "filbench|global_mmlu_all_tgl_mcf:anatomy|0|0" \
# --custom-tasks community_tasks/filbench_evals.py
